image:
  repository: ghcr.io/gaurangkudale/rca-operator-microservice-demo-app
  tag: main
  pullPolicy: Always

loadTesterImage:
  repository: ghcr.io/gaurangkudale/rca-operator-microservice-demo-load-tester
  tag: main
  pullPolicy: Always

services:
  - name: frontend
    env:
      - name: NEXT_SERVICE_URL
        value: "http://cart-service:8080"
      - name: VALIDATE_SERVICES_URL
        value: "http://ad-service:8080"
      - name: FETCH_SERVICES_URL
        value: "http://product-catalog-service:8080"
      - name: VERIFY_SERVICES_URL
        value: "http://recommendation-service:8080"
      - name: CHECK_SERVICES_URL
        value: "http://checkout-service:8080, http://cart-service:8080"

  - name: product-catalog-service
    env:
      - name: VALIDATE_SERVICES_URL
        value: "http://product-reviews-service:8080"
      - name: FETCH_SERVICES_URL
        value: "http://product-reviews-service:8080"
      - name: VERIFY_SERVICES_URL
        value: "http://recommendation-service:8080"
      - name: CHECK_SERVICES_URL
        value: "http://inventory-service:8080"

  - name: product-reviews-service
    env:
      - name: VALIDATE_SERVICES_URL
        value: "http://product-catalog-service:8080"
      - name: FETCH_SERVICES_URL
        value: "http://product-catalog-service:8080"
      - name: VERIFY_SERVICES_URL
        value: "http://recommendation-service:8080"
      - name: CHECK_SERVICES_URL
        value: "http://product-catalog-service:8080"

  - name: recommendation-service
    env:
      - name: VALIDATE_SERVICES_URL
        value: "http://product-catalog-service:8080"
      - name: FETCH_SERVICES_URL
        value: "http://product-reviews-service:8080"
      - name: VERIFY_SERVICES_URL
        value: "http://quote-service:8080"
      - name: CHECK_SERVICES_URL
        value: "http://product-catalog-service:8080"

  - name: ad-service
    env:
      - name: NEXT_SERVICE_URL
        value: "http://recommendation-service:8080"
      - name: VALIDATE_SERVICES_URL
        value: "http://recommendation-service:8080"
      - name: FETCH_SERVICES_URL
        value: "http://recommendation-service:8080"
      - name: VERIFY_SERVICES_URL
        value: "http://product-catalog-service:8080"
      - name: CHECK_SERVICES_URL
        value: "http://recommendation-service:8080"

  - name: cart-service
    env:
      - name: NEXT_SERVICE_URL
        value: "http://checkout-service:8080"
      - name: VALIDATE_SERVICES_URL
        value: "http://product-catalog-service:8080"
      - name: FETCH_SERVICES_URL
        value: "http://product-catalog-service:8080, http://product-reviews-service:8080"
      - name: VERIFY_SERVICES_URL
        value: "http://quote-service:8080"
      - name: CHECK_SERVICES_URL
        value: "http://checkout-service:8080"

  - name: checkout-service
    env:
      - name: NEXT_SERVICE_URL
        value: "http://payment-service:8080"
      - name: VALIDATE_SERVICES_URL
        value: "http://cart-service:8080, http://quote-service:8080"
      - name: FETCH_SERVICES_URL
        value: "http://cart-service:8080, http://quote-service:8080"
      - name: VERIFY_SERVICES_URL
        value: "http://payment-service:8080, http://shipping-service:8080"
      - name: CHECK_SERVICES_URL
        value: "http://email-service:8080, http://accounting-service:8080"

  - name: payment-service
    env:
      - name: NEXT_SERVICE_URL
        value: "http://accounting-service:8080"
      - name: VALIDATE_SERVICES_URL
        value: "http://accounting-service:8080"
      - name: FETCH_SERVICES_URL
        value: "http://accounting-service:8080"
      - name: VERIFY_SERVICES_URL
        value: "http://accounting-service:8080"
      - name: CHECK_SERVICES_URL
        value: "http://accounting-service:8080"

  - name: shipping-service
    env:
      - name: VALIDATE_SERVICES_URL
        value: "http://quote-service:8080"
      - name: FETCH_SERVICES_URL
        value: "http://quote-service:8080"
      - name: VERIFY_SERVICES_URL
        value: "http://quote-service:8080"
      - name: CHECK_SERVICES_URL
        value: "http://quote-service:8080"

  - name: quote-service
    env:
      - name: VALIDATE_SERVICES_URL
        value: "http://inventory-service:8080"
      - name: FETCH_SERVICES_URL
        value: "http://inventory-service:8080"
      - name: VERIFY_SERVICES_URL
        value: "http://inventory-service:8080"
      - name: CHECK_SERVICES_URL
        value: "http://inventory-service:8080"

  - name: email-service
    env:
      - name: CHECK_SERVICES_URL
        value: "http://frontend:8080"

  - name: accounting-service
    env:
      - name: CHECK_SERVICES_URL
        value: "http://payment-service:8080"

  - name: inventory-service
    env:
      - name: CHECK_SERVICES_URL
        value: "http://product-catalog-service:8080"

# Dependencies
postgresql:
  enabled: true
  image:
    registry: docker.io
    repository: library/postgres
    tag: "15-alpine"
    pullPolicy: IfNotPresent
  auth:
    username: "postgres"
    postgresPassword: "password"
    database: "rca_demo"

prometheus:
  enabled: false

signoz:
  enabled: false # Disabled by default as it's heavy, enable if needed
